# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y4MbZ-OJCD6Hl6ThoeIkZ-2ZGBU7dMLR
"""

import numpy as np
import pandas as pd
import os

# Commented out IPython magic to ensure Python compatibility.
# %config Compeleter.user_jedi =False

import torch
torch.__version__

import fastai
fastai.__version__

from fastai import *
from fastai.vision import *
from fastai.vision.all import *

import os
os.environ['CONFIG_DIR']='/content/drive/MyDrive'

import zipfile

zip_file_path = '/content/drive/MyDrive/flowers.zip'  # replace with the path to your ZIP file
destination_folder_path = '/content/drive/MyDrive'  # replace with the path to your destination folder

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(destination_folder_path)

data_path = '/content/drive/MyDrive/flowers'

tfms_for_item = RandomResizedCrop(128, min_scale=0.35)

tfms_for_batch = [Normalize.from_stats(*imagenet_stats)]

dsl = ImageDataLoaders.from_folder(data_path, item_tfms=tfms_for_item,
                                    batch_tfms=tfms_for_batch,
                                    valid_pct=0.15, shuffle=True,
                                    device=torch.device('cuda'))

dsl.show_batch(figsize=(14,10))

#number of classes
dsl.c

learn = cnn_learner(dsl, resnet50, metrics=accuracy,model_dir='/tmp/model/')

learn.summary()

learn.lr_find()

learn.fit_one_cycle(20, 0.000691)
#train_loss and validation_loss decreased, accuracy increased, model getting better

learn.save('model.pkl')

learn.show_results()

interp = Interpretation.from_learner(learn)

interp.plot_top_losses(9, figsize=(15,10))

interp2=ClassificationInterpretation.from_learner(learn)

interp2.plot_confusion_matrix(figsize=(12,12),dpi=60) #dot per image - don't touch

interp2.most_confused(min_val=2)

